# server configuration
server:
  port: 9191

# endpoint configuration
endpoints:
  shutdown:
    enabled: true

# database configuration
spring:
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mysql:thin://localhost:3306/messagegateway
    username: root
    password: mysql
    driverClassName: org.drizzle.jdbc.DrizzleDriver
  
  flyway:
    schemas: messagegateway
    baseline-on-migrate: true #NEVER CHANGE BASELINE TO TRUE
    validate-on-migrate: true #true to populate local DB
    table: schema_version
    enabled: true

# Status Callback configuration for Twilio. Port will be taken from server configuration
hostconfig:
  host-address: localhost
  protocol: http
